### ISSUE TITLE
Suggestion: Use device name as UID instead of IP address

### ISSUE THREAD

**Issue by salsabeard** [willholdoway/hifiberry#14]
I just migrated my 3 devices from Balena-Sound to HiFiBerry OS.  I can't believe I held out as long as I did as this platform is exactly what I've wanted.

My suggestion is based around two different use-case scenarios.  One would be for users that are simply using DHCP for addressing of the HFB.  Given that the address is subject to change, it isn't a viable UID.  

The second use-case is the one I fall into.  I have static addresses assigned for my devices, but I also utilize both wired and wireless.  In both Balena-Sound and HiFiBerry OS, the devices seem to connect to wireless even when the wired is connected.  This results in the device pulling two IP addresses.

As such, I end up having 6 different devices with single entities for 3 physical units.  It would be nice if each unit was tracked as a single device with a data table consisting of the relevant MAC addresses.  IP would be populated dynamically via ARP.  Then we'd just need the media player entity to track whichever MAC is actively in use for the device.

**Comment by willholdoway** [comment]
This is defined by hifiberry you would have to ask over there and @schnabel would have to help implement in audiocontrol2sio

**Comment by schnabel** [comment]
@salsabeard if you are still interested ... let me know. But I do not have a lot of time at the moment :-(.

**Comment by schnabel** [comment]
Hi @salsabeard, 
I think your problem might just be a small misunderstanding. If I understand correctly you want to abstract away from the physical connection used to communicate from HASS with the hifiberry API.
You could use the name of the hifiberry devices instead of fixed IPs (in the HASS config). This name should be used by your router for your LAN (for DNS). You can configure the name in main view of the hifiberry os (the three dots). In case you want to disable wifi ... you can do that in the network settings. 
Hope that solves your problem :-).

**Comment by salsabeard** [comment]
Definitely not a misunderstanding. I am a network engineer and I know how hostname and address resolution work, but a fair number do not, nor do they know how to setup a local DNS server.This also still doesn’t really solve the issue as the name server should only be returning one address per hostname, and the HiFiBerry will technically have two if both wired and wireless interfaces are enabled and connected.  Technically this should be up to logic in the HFB to disable wireless if wired is connected (and it may be there but I haven’t checked in a long while).-In the HASS integration, the idea would be that some other property would be used as the unique identifier for the devices, and the list of current associated IP addresses would be more of a transient property. But again, there really isn’t a good way to update it if it changes, short of leveraging a discovery protocol such as SSDP.-NickOn Apr 14, 2024, at 5:46 AM, schnabel ***@***.***> wrote:﻿
Hi @salsabeard,
I think your problem might just be a small misunderstanding. If I understand correctly you want to abstract away from the physical connection used to communicate from HASS with the hifiberry API.
You could use the name of the hifiberry devices instead of fixed IPs (in the HASS config). This name should be used by your router for your LAN (for DNS). You can configure the name in main view of the hifiberry os (the three dots). In case you want to disable wifi ... you can do that in the network settings.
Hope that solves your problem :-).

**Comment by schnabel** [comment]
HI @salsabeard. I did not mean offend you or question your knowledge about networking. I assumed from your first post that you might think you have to use an IP to configure the HFB in HASS. That is why I pointed out that you could use DNS if your router supports it.
I also think it is a valid assumption that many user do use a router with DNS and in that case it would solve the problem. Since it is possible to turn off the wifi on the hifiberry I do not really see much need for action.

**Comment by salsabeard** [comment]
Oh, I am sorry if I seemed offended. I was simply trying to convey my understanding. Using the hostname and DNS is a perfectly viable option, though I do think static IP addressing or DHCP reservations would be easier.But I do also agree. The issue is not really worth the time it would take to improve it as it stands currently. It really is working well enough for 95% of use cases. Honestly, I think this can just get closed out fully. There isn’t really much else to do with it.-NickOn Apr 14, 2024, at 1:09 PM, schnabel ***@***.***> wrote:﻿
HI @salsabeard. I did not mean offend you or question your knowledge about networking. I assumed from your first post that you might think you have to use an IP to configure the HFB in HASS. That is why I pointed out that you could use DNS if your router supports it.
I also think it is a valid assumption that many user do use a router with DNS and in that case it would solve the problem. Since it is possible to turn off the wifi on the hifiberry I do not really see much need for action.
