### ISSUE TITLE
Can't add device

### ISSUE THREAD

**Issue by fjfricke** [willholdoway/hifiberry#16]
Getting this error:

```
Logger: custom_components.hifiberry.config_flow
Source: custom_components/hifiberry/config_flow.py:23 
Integration: hifiberry (documentation) 
First occurred: 00:15:29 (3 occurrences) 
Last logged: 00:53:34

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/hifiberry/config_flow.py", line 69, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/hifiberry/config_flow.py", line 23, in validate_input
    await Audiocontrol2SIO.connect(host=data["host"], port=data["port"])
  File "/usr/local/lib/python3.9/site-packages/pyhifiberry/audiocontrol2sio.py", line 38, in connect
    await sio.connect(f'http://{host}:{port}', wait_timeout=wait_timeout)
TypeError: connect() got an unexpected keyword argument 'wait_timeout'

```

**Comment by fjfricke** [comment]
I think this is due to the fact that pyhifiberry version 0.0.4 is still used instead of 0.1.0.

**Comment by schnabel** [comment]
Hi @fjfricke 
unfortunately the homeassistant guys pinned the python-socketio version to an older version than pyhifiberry needs. If you are interested in details have a look at [this issue](https://github.com/home-assistant/core/issues/69349). Because they will not revert this in favor of hifiberry I have to make a pyhifiberry release that includes python-socketio code as recommended [here](https://github.com/miguelgrinberg/python-socketio/discussions/909).
