### ISSUE TITLE
Cannot add hifiberry device: "Failed to connect"

### ISSUE THREAD

**Issue by fjfricke** [willholdoway/hifiberry#18]
With the new version released, I can still not add a new integration. Getting this error:

`
Logger: homeassistant
Source: runner.py:96 
First occurred: 13:31:24 (1 occurrences) 
Last logged: 13:31:24

Error doing job: Unclosed client session
`

**Comment by fjfricke** [comment]
I think it has something to do with my setup so I'll try to reinstall home assistant.

**Comment by fjfricke** [comment]
CAn't get it running.. Do you know how I can get more logs?

**Comment by malteger** [comment]
I think this is happening because of the switch to the socketio API. I have enabled it in the hifiberry device according to https://github.com/hifiberry/audiocontrol2/blob/master/doc/socketio_api.md and after that it was working again. It would be a good idea if the documentation could be updated.

@schnabel Am I correct that with your PR the old REST API is no longer supported?

**Comment by fjfricke** [comment]
perfect! That helped :)

**Comment by schnabel** [comment]
@malteger @fjfricke Sorry for the confusion. I am going to write some documentation! This story was a nightmare that went on for a few month because five different repositories were involved. Great that it finally works for you. Do you uses HACS? I hope @willholdoway can now start making it a HA core integration :-).

**Comment by malteger** [comment]
@schnabel No, I am using it by cloning the repository and copying files, with that I also see which changes have been done.

Nice work with the socketio implementation, a saw all the other PRs to get this working and remembered that the hifiberry maintainer was not going with having socketio enabled by default. I think this is a slight problem for people who have not so much technical knowledge, that is the reason I asked about the REST API, as that is enabled by default (I think, don't remember).

**Comment by schnabel** [comment]
Yes, the REST API is always enabled. It might be a good idea to use it as fallback API here. @willholdoway what do you think? On the other hand, I will write the documentation tomorrow and whoever uses a this setup is probably able to follow the instructions.

**Comment by willholdoway** [comment]
Fallnback API tricky. I always like resilience but it's a very different product and while the fallback is in action we'll be getting all the old log bloating etc
